name: Regression Tests DevPortal - UI and API

on:
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 11 * * *' # Run every day at 11a.m

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        USER_NAME: ${{ secrets.USER_NAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
      run: npx playwright test

    - name: Upload Playwright Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: report-automation-devportal
        path: playwright-report/
        retention-days: 30
